Fix shUnit2 assert behavior with bash -e option
assertTrue, assertFalse, etc did not work well with that option enabled.
However, that bash option improves vastly the test suit, allowing us to
detect failures earlier.

It exists a patch that fix this behavior in
https://github.com/kward/shunit2/issues/37. Until shUnit merges it, we
will apply that patch in docker creation.

diff --git a/tests/ubuntu-16.04/Dockerfile b/tests/ubuntu-16.04/Dockerfile
--- a/tests/ubuntu-16.04/Dockerfile
+++ b/tests/ubuntu-16.04/Dockerfile
@@ -30,11 +30,23 @@ RUN make -j 2 kcov
 FROM ubuntu:16.04
 
 RUN apt update && apt install --no-install-recommends -y \
+	ca-certificates \
+	curl \
 	kafkacat \
 	libdw1 \
 	make \
+	patch \
 	pslist \
 	shunit2 \
 	socat
+
+# Patch socat to not to fail in AssertTrue
+RUN [ "/bin/bash", "-c", \
+	"set -o pipefail && patch=$(mktemp) && \
+    curl -L https://storage.googleapis.com/google-code-attachments/shunit2/issue-37/comment-1/assertTrue_assertFalse_error.patch \
+        >\"$patch\" && \
+    md5sum -c --status <(printf '%s  %s' '65f8947f5f43c577f110db915c7801d6' \"$patch\") && \
+    patch -d /usr/bin < \"$patch\" && \
+    rm -f \"$patch\"" ]
 
 COPY --from=builder /kcov/kcov-35/build/src/kcov /usr/local/bin/kcov
